name: LLMs CI

on: 
  workflow_dispatch:

jobs:
  llms_specs:
    runs-on: ubuntu-latest
    env:
      OPENAI_ACCESS_TOKEN: ${{ secrets.OPENAI_ACCESS_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Install gems
        run: bundle install
      - name: Run rspec
        run: bundle exec rspec spec/llms

